//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazarStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Brand_ID { get; set; }
        public string Description { get; set; }
        public string Image_URL { get; set; }
        public string Product_ID { get; set; }
        public Nullable<decimal> Discount_Price__in_Rs__ { get; set; }
        public Nullable<decimal> Original_Price__in_Rs__ { get; set; }
        public string Product_URL { get; set; }
        public string Category_by_gender_ID { get; set; }
        public string Category_ID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual CategoryByGender CategoryByGender { get; set; }
    }
}
